---
USER_ID_PREFIX: EMP
ASSET_ID_PREFIX: ASN
VENDOR_ID_PREFIX: VEN
CATEGORY_ID_PREFIX: CAT
ISSUE_ID_PREFIX: ISN
MAPPING_ID_PREFIX: MPN

CONFLICT_MSG: Conflict
INTERNAL_SERVER_ERROR: Internal server error
RESOURCE_NOT_FOUND: Resource not found
UNAUTHORISED: Unauthorised
BAD_REQUEST: Bad request
UNPROCESSIBLE_ENTITY: Unprocessible entity

USERNAME_EXISTS: Username already exists
SERVER_ERROR: Server not responding. Try again after some time
VENDOR_NOT_EXISTS: Vendor not exists to deactivate
USER_NOT_EXISTS: User not exists in database
INVALID_CREDENTIALS_ENTERED: Invalid credentials entered
PASSWORDS_NOT_MATCH: New password and old password do not match
ASSETS_NOT_EXISTS: No assets available in inventory
CATEGORY_NOT_EXISTS: Category not exists in database
ASSET_ID_NOT_EXISTS: Asset id not exists
VENDOR_ALREADY_EXISTS: Vendor already exists in database
CATEGORY_ALREADY_EXISTS: Category already exists in database
ISSUE_ALREADY_EXISTS: Issue already exists
ISSUE_NOT_EXISTS: No issues available
ASSET_CREATED: Asset created in inventory successfully
ASSET_ASSIGNED: Asset assigned to user successfully
ASSET_UNASSIGNED: Asset unassigned from user successfully
USER_LOGGED_IN : User logged in successfully
CATEGORY_CREATED : Category created successfully
ISSUE_CREATED : Issue created successfully
USER_CREATED : User created successfully
PASSWORD_UPDATED : Password updated successfully
VENDOR_CREATED : Vendor created successfully
VENDOR_DEACTIVATED : Vendor deactivated successfully

SUCCESS_REPONSE : Request is successfull
USER_DATA_FETCHED : User details fetched
CATEGORY_DATA_FETCHED : Category details fetched
ISSUE_DATA_FETCHED : Issue details fetched
ISSUE_USER_DATA_FETCHED : Issue details of any user fetched
ASSET_DATA_FETCHED : Assets in inventory fetched
VENDOR_DATA_FETCHED : Vendor details fetched
ISSUE_ALREADY_RESOLVED : Issue already resolved
CUSTOM_ERROR_MSG : My custom error message
ISSUE_RESOLVED : Issue resolved successfully
USER_LOGGED_OUT : User logged out successfully
INVALID_USER_ID : User id entered is not of valid format
INVALID_ISSUE_ID : Issue id entered is not of valid format
INVALID_VENDOR_ID: Vendor id entered is not of valid format
INVALID_ASSET_ID: Asset id entered is not of valid format
...