#common
LOG_INVALID_INPUT : Invalid input entered
LOG_CATEGORY_ADDED : Category added in database
LOG_VENDOR_ADDED : Vendor added in database
LOG_STARTING_APPLICATION : Starting with asset management system.
LOG_EXITING_APPLICATION : Connection closed. Exiting from application

#auth logs
LOG_LOGIN_EXHAUSTED : Login attempts are exhausted
LOG_LOGIN_ATTEMPTS_RESETTING : Login attempts are resetting
LOG_LOGIN_ATTEMPT_REDUCING : login attempts are reducing due to invalid login
PROVIDE_ROLE_BASED_ACCESS : Providing role based access to authenticated user
LOG_INVALID_LOGIN : Invalid login occured
LOG_DEFAULT_PASSWORD : User changed default password

#admin
LOG_ADMIN_MENU : Admin menu displayed
LOG_TO_DEACTIVATE_VENDOR : Trying to deactivate vendor
LOG_CREATE_NEW_USER : Create new user
LOG_ADMIN_LOGGED_IN : Admin logged in the system
LOG_VENDOR_DEACTIVATED : Vendor deactivated successfully
LOG_ADMIN_LOGGED_OUT : Admin logged out
LOG_USER_CREATED : New user created successfully

#asset_data
LOG_VENDOR_DISPLAYED : Displays vendors of the system
LOG_CATEGORY_DISPLAYED : Displays category of the system

#database
LOG_ERROR_CONNECTING_DATABASE : Error occured while connecting to database

#employee 
LOG_EMPLOYEE_MENU : Employee menu displayed
LOG_EMPLOYEE_LOGGED_OUT : Employee logged out of the system
LOG_ISSUE_RAISED : Issue raised successfully
LOG_EMPLOYEE_LOGGED_IN : Employee logged in the system

#manager
LOG_MANAGER_LOGGED_IN : Asset Manager logged in the system
LOG_MANAGER_MENU : Manager menu displayed
LOG_ASSET_ADDED : Asset successfully added
LOG_ASSET_ASSIGNED : Asset assigned successfully to user
LOG_ASSET_UNASSIGNED : Asset unassigned from the user
ASSET_SEND_MAINTENANCE : Asset send for maintenance
ASSET_RECIEVED_MAINTENANCE : Asset receieved from maintenance
LOG_ASSET_ADDED_INVENTORY : New asset added to inventory

#validations
LOG_INVALID_NAME : Invalid name entered
LOG_INVALID_EMAIL : Invalid email entered
LOG_INVALID_PASSWORD : Invalid password entered
LOG_INVALID_USER_ID : Invalid user id entered
LOG_INVALID_ASSET_ID : Inavlid asset id entered
LOG_INVALID_VENDOR_ID : Invalid vendor id entered
LOG_INVALID_CATEGORY_ID : Invalid category id entered
LOG_INVALID_MAPPING_ID : Invalid mapping id entered
LOG_INVALID_ISSUE_ID : Invalid issue id entered
LOG_INVALID_MAINTENANCE_ID : Invalid maintenance id entered
LOG_INVALID_DATE : Invalid date entered
